[2023-08-23T13:30:25.261+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: tbf_analysis_dag_v14.create_dataproc_cluster_task manual__2023-08-23T05:07:46.845506+00:00 [queued]>
[2023-08-23T13:30:25.267+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: tbf_analysis_dag_v14.create_dataproc_cluster_task manual__2023-08-23T05:07:46.845506+00:00 [queued]>
[2023-08-23T13:30:25.267+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-08-23T13:30:25.268+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-08-23T13:30:25.268+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-08-23T13:30:25.276+0000] {taskinstance.py:1383} INFO - Executing <Task(DataprocCreateClusterOperator): create_dataproc_cluster_task> on 2023-08-23 05:07:46.845506+00:00
[2023-08-23T13:30:25.282+0000] {standard_task_runner.py:54} INFO - Started process 42604 to run task
[2023-08-23T13:30:25.288+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'tbf_analysis_dag_v14', 'create_dataproc_cluster_task', 'manual__2023-08-23T05:07:46.845506+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/tbf_analysis_dag_v14.py', '--cfg-path', '/tmp/tmpwr7sr7q7']
[2023-08-23T13:30:25.290+0000] {standard_task_runner.py:83} INFO - Job 11: Subtask create_dataproc_cluster_task
[2023-08-23T13:30:25.291+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/tbf_analysis_dag_v14.py
[2023-08-23T13:30:25.293+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task create_dataproc_cluster_task (Dag 'tbf_analysis_dag_v14' could not be found; either it does not exist or it failed to parse.; 42604)
[2023-08-23T13:30:25.302+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-08-23T13:30:25.322+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
