[2023-08-22T00:26:31.581+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: tbf_analysis_dag_v10.transfer_to_GCS_task scheduled__2023-08-22T00:00:00+00:00 [queued]>
[2023-08-22T00:26:31.586+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: tbf_analysis_dag_v10.transfer_to_GCS_task scheduled__2023-08-22T00:00:00+00:00 [queued]>
[2023-08-22T00:26:31.587+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-08-22T00:26:31.588+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-08-22T00:26:31.588+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-08-22T00:26:31.595+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): transfer_to_GCS_task> on 2023-08-22 00:00:00+00:00
[2023-08-22T00:26:31.601+0000] {standard_task_runner.py:54} INFO - Started process 250 to run task
[2023-08-22T00:26:31.604+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'tbf_analysis_dag_v10', 'transfer_to_GCS_task', 'scheduled__2023-08-22T00:00:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/tbf_analysis_dag_v10.py', '--cfg-path', '/tmp/tmp7o6rehr3']
[2023-08-22T00:26:31.606+0000] {standard_task_runner.py:83} INFO - Job 70: Subtask transfer_to_GCS_task
[2023-08-22T00:26:31.607+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/tbf_analysis_dag_v10.py
[2023-08-22T00:26:31.661+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-08-22T00:26:31.699+0000] {task_command.py:384} INFO - Running <TaskInstance: tbf_analysis_dag_v10.transfer_to_GCS_task scheduled__2023-08-22T00:00:00+00:00 [running]> on host 2791cbd3eb46
[2023-08-22T00:26:31.750+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tbf_analysis_dag_v10
AIRFLOW_CTX_TASK_ID=transfer_to_GCS_task
AIRFLOW_CTX_EXECUTION_DATE=2023-08-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-22T00:00:00+00:00
[2023-08-22T00:26:31.751+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-08-22T00:26:31.752+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'bash /opt/***/transfer_to_GCS/gcloud_setup_local.sh tbf-analysis-terraform_trans-border-freights-394419']
[2023-08-22T00:26:31.763+0000] {subprocess.py:86} INFO - Output:
[2023-08-22T00:26:33.215+0000] {subprocess.py:93} INFO - CommandException: No URLs matched: transfer_to_GCS/02a_transform_consolidate.py
[2023-08-22T00:26:34.530+0000] {subprocess.py:93} INFO - CommandException: No URLs matched: transfer_to_GCS/02b_transform_joinwithmetadata.py
[2023-08-22T00:26:35.771+0000] {subprocess.py:93} INFO - CommandException: No URLs matched: transfer_to_GCS/TransBorderCodes.xls
[2023-08-22T00:26:35.917+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-22T00:26:35.929+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-22T00:26:35.932+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=tbf_analysis_dag_v10, task_id=transfer_to_GCS_task, execution_date=20230822T000000, start_date=20230822T002631, end_date=20230822T002635
[2023-08-22T00:26:35.942+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 70 for task transfer_to_GCS_task (Bash command failed. The command returned a non-zero exit code 1.; 250)
[2023-08-22T00:26:35.994+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-08-22T00:26:36.017+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
