ahegde@terraform-instance:~/TransBorderFreight-pySpark-BigQuery-Looker/Airflow$ docker compose up airflow-init
[+] Running 3/3
 ✔ Network airflow_default           Created                                                                                                    0.1s
 ✔ Container airflow-redis-1         Created                                                                                                    0.1s
 ✔ Container airflow-airflow-init-1  Created                                                                                                    0.0s
Attaching to airflow-airflow-init-1, airflow-redis-1
airflow-redis-1         | 1:C 18 Aug 2023 05:34:26.728 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
airflow-redis-1         | 1:C 18 Aug 2023 05:34:26.728 * Redis version=7.2.0, bits=64, commit=00000000, modified=0, pid=1, just started
airflow-redis-1         | 1:C 18 Aug 2023 05:34:26.728 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
airflow-redis-1         | 1:M 18 Aug 2023 05:34:26.729 * monotonic clock: POSIX clock_gettime
airflow-redis-1         | 1:M 18 Aug 2023 05:34:26.730 * Running mode=standalone, port=6379.
airflow-redis-1         | 1:M 18 Aug 2023 05:34:26.730 * Server initialized
airflow-redis-1         | 1:M 18 Aug 2023 05:34:26.730 * Ready to accept connections tcp
airflow-airflow-init-1  | /home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
airflow-airflow-init-1  |   option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)
airflow-airflow-init-1  | /home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py:545: DeprecationWarning: The auth_backend option in [api] has been renamed to auth_backends - the old setting has been used, but please update your config.
airflow-airflow-init-1  |   option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)
airflow-airflow-init-1  | /home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py:367: FutureWarning: The auth_backends setting in [api] has had airflow.api.auth.backend.session added in the running config, which is needed by the UI. Please update your config before Apache Airflow 3.0.
airflow-airflow-init-1  |   FutureWarning,
airflow-airflow-init-1  |
airflow-airflow-init-1  |
airflow-airflow-init-1  | WARNING!!!: Not enough Disk space available for Docker.
airflow-airflow-init-1  | At least 10 GBs recommended. You have 1.4G
airflow-airflow-init-1  |
airflow-airflow-init-1  |
airflow-airflow-init-1  |
airflow-airflow-init-1  | WARNING!!!: You have not enough resources to run Airflow (see above)!
airflow-airflow-init-1  | Please follow the instructions to increase amount of resources available:
airflow-airflow-init-1  |    https://airflow.apache.org/docs/apache-airflow/stable/start/docker.html#before-you-begin
airflow-airflow-init-1  |
airflow-airflow-init-1  |
airflow-airflow-init-1  | The container is run as root user. For security, consider using a regular user account.
airflow-airflow-init-1  | .
airflow-airflow-init-1  | .
airflow-airflow-init-1  | .
airflow-airflow-init-1  | .
airflow-airflow-init-1  | .
airflow-airflow-init-1  | .
airflow-airflow-init-1  | .
airflow-airflow-init-1  | .
airflow-airflow-init-1  | .
airflow-airflow-init-1  | .
airflow-airflow-init-1  | .
airflow-airflow-init-1  | .
airflow-airflow-init-1  | .
airflow-airflow-init-1  | .
airflow-airflow-init-1  | .
airflow-airflow-init-1  | .
airflow-airflow-init-1  | .
airflow-airflow-init-1  | .
airflow-airflow-init-1  | .
airflow-airflow-init-1  | .
airflow-airflow-init-1  | ERROR! Maximum number of retries (20) reached.
airflow-airflow-init-1  |
airflow-airflow-init-1  | Last check result:
airflow-airflow-init-1  | $ airflow db check
airflow-airflow-init-1  |
airflow-airflow-init-1  | /home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
airflow-airflow-init-1  |   option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)
airflow-airflow-init-1  | /home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py:545: DeprecationWarning: The auth_backend option in [api] has been renamed to auth_backends - the old setting has been used, but please update your config.
airflow-airflow-init-1  |   option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)
airflow-airflow-init-1  | /home/airflow/.local/lib/python3.7/site-packages/airflow/configuration.py:367: FutureWarning: The auth_backends setting in [api] has had airflow.api.auth.backend.session added in the running config, which is needed by the UI. Please update your config before Apache Airflow 3.0.
airflow-airflow-init-1  |   FutureWarning,
airflow-airflow-init-1  | [2023-08-18 05:35:49,930] {cli_action_loggers.py:125} WARNING - Failed to log action with (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution
airflow-airflow-init-1  |
airflow-airflow-init-1  | (Background on this error at: https://sqlalche.me/e/14/e3q8)
airflow-airflow-init-1  | Traceback (most recent call last):
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
airflow-airflow-init-1  |     return fn()
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
airflow-airflow-init-1  |     return _ConnectionFairy._checkout(self)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
airflow-airflow-init-1  |     fairy = _ConnectionRecord.checkout(pool)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
airflow-airflow-init-1  |     rec = pool._do_get()
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
airflow-airflow-init-1  |     self._dec_overflow()
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
airflow-airflow-init-1  |     with_traceback=exc_tb,
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
airflow-airflow-init-1  |     raise exception
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
airflow-airflow-init-1  |     return self._create_connection()
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
airflow-airflow-init-1  |     return _ConnectionRecord(self)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
airflow-airflow-init-1  |     self.__connect()
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
airflow-airflow-init-1  |     pool.logger.debug("Error on connect(): %s", e)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
airflow-airflow-init-1  |     with_traceback=exc_tb,
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
airflow-airflow-init-1  |     raise exception
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
airflow-airflow-init-1  |     self.dbapi_connection = connection = pool._invoke_creator(self)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
airflow-airflow-init-1  |     return dialect.connect(*cargs, **cparams)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
airflow-airflow-init-1  |     return self.dbapi.connect(*cargs, **cparams)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
airflow-airflow-init-1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
airflow-airflow-init-1  | psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution
airflow-airflow-init-1  |
airflow-airflow-init-1  |
airflow-airflow-init-1  | The above exception was the direct cause of the following exception:
airflow-airflow-init-1  |
airflow-airflow-init-1  | Traceback (most recent call last):
airflow-airflow-init-1  |   File "/home/airflow/.local/bin/airflow", line 8, in <module>
airflow-airflow-init-1  |     sys.exit(main())
airflow-airflow-init-1  |   File "/home/airflow/.local/l
airflow-airflow-init-1  | ib/python3.7/site-packages/airflow/__main__.py", line 39, in main
airflow-airflow-init-1  |     args.func(args)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 52, in command
airflow-airflow-init-1  |     return func(*args, **kwargs)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 99, in wrapper
airflow-airflow-init-1  |     return f(*args, **kwargs)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/db_command.py", line 187, in check
airflow-airflow-init-1  |     db.check()
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
airflow-airflow-init-1  |     return func(*args, session=session, **kwargs)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/db.py", line 1679, in check
airflow-airflow-init-1  |     session.execute('select 1 as is_alive;')
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
airflow-airflow-init-1  |     conn = self._connection_for_bind(bind)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1530, in _connection_for_bind
airflow-airflow-init-1  |     engine, execution_options
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
airflow-airflow-init-1  |     conn = bind.connect()
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3197, in connect
airflow-airflow-init-1  |     return self._connection_cls(self, close_with_result=close_with_result)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
airflow-airflow-init-1  |     else engine.raw_connection()
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3276, in raw_connection
airflow-airflow-init-1  |     return self._wrap_pool_connect(self.pool.connect, _connection)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3247, in _wrap_pool_connect
airflow-airflow-init-1  |     e, dialect, self
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2101, in _handle_dbapi_exception_noconnection
airflow-airflow-init-1  |     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
airflow-airflow-init-1  |     raise exception
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
airflow-airflow-init-1  |     return fn()
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 310, in connect
airflow-airflow-init-1  |     return _ConnectionFairy._checkout(self)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
airflow-airflow-init-1  |     fairy = _ConnectionRecord.checkout(pool)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
airflow-airflow-init-1  |     rec = pool._do_get()
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
airflow-airflow-init-1  |     self._dec_overflow()
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
airflow-airflow-init-1  |     with_traceback=exc_tb,
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
airflow-airflow-init-1  |     raise exception
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
airflow-airflow-init-1  |     return self._create_connection()
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
airflow-airflow-init-1  |     return _ConnectionRecord(self)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
airflow-airflow-init-1  |     self.__connect()
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
airflow-airflow-init-1  |     pool.logger.debug("Error on connect(): %s", e)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
airflow-airflow-init-1  |     with_traceback=exc_tb,
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
airflow-airflow-init-1  |     raise exception
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
airflow-airflow-init-1  |     self.dbapi_connection = connection = pool._invoke_creator(self)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 590, in connect
airflow-airflow-init-1  |     return dialect.connect(*cargs, **cparams)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 584, in connect
airflow-airflow-init-1  |     return self.dbapi.connect(*cargs, **cparams)
airflow-airflow-init-1  |   File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
airflow-airflow-init-1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
airflow-airflow-init-1  | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution
airflow-airflow-init-1  |
airflow-airflow-init-1  | (Background on this error at: https://sqlalche.me/e/14/e3q8)
